param(
    [switch]$UseDefaults,
    [switch]$SkipStart,
    [int]$ConsolePort,
    [int]$ApiPort,
    [int]$GatewayPort,
    [string]$FrontendIp,
    [int]$FrontendPort,
    [string]$BackendIp,
    [int]$BackendPort,
    [string]$DefaultSiteKey,
    [string]$DefaultSiteName,
    [string]$DisplaySiteLabel,
    [string]$DomainCode
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::UTF8
$OutputEncoding = [System.Text.UTF8Encoding]::UTF8

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$packageRoot = Split-Path -Parent $scriptDir
$configDir = Join-Path $packageRoot 'config'
$dataDir = Join-Path $packageRoot 'ids-data'
$stateDir = Join-Path $dataDir 'state'
$envExamplePath = Join-Path $configDir 'ids-backend.env.example'
$envPath = Join-Path $configDir 'ids-backend.env'
$statePath = Join-Path $stateDir 'communication_settings.json'
$composePath = Join-Path $packageRoot 'docker-compose.generated.yml'

New-Item -ItemType Directory -Force -Path $configDir | Out-Null
New-Item -ItemType Directory -Force -Path $stateDir | Out-Null

function Write-Section {
    param(
        [string]$Title,
        [string]$Description = ''
    )

    Write-Host ''
    Write-Host ('=' * 72) -ForegroundColor DarkCyan
    Write-Host $Title -ForegroundColor Cyan
    if ($Description) {
        Write-Host $Description -ForegroundColor Gray
    }
    Write-Host ('=' * 72) -ForegroundColor DarkCyan
}

function Get-PropValue {
    param(
        $Object,
        [string]$Name,
        $Default = $null
    )

    if ($null -eq $Object) {
        return $Default
    }

    if ($Object -is [System.Collections.IDictionary]) {
        if ($Object.Contains($Name)) {
            return $Object[$Name]
        }
        return $Default
    }

    $property = $Object.PSObject.Properties[$Name]
    if ($null -ne $property) {
        return $property.Value
    }

    return $Default
}

function Read-JsonFile {
    param(
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return $null
    }

    try {
        return Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json
    } catch {
        Write-Host "[warn] 无法读取 JSON 文件: $Path" -ForegroundColor Yellow
        return $null
    }
}

function As-Array {
    param(
        $Value
    )

    if ($null -eq $Value) {
        return @()
    }

    if ($Value -is [string]) {
        return @($Value)
    }

    if ($Value -is [System.Collections.IEnumerable]) {
        return @($Value)
    }

    return @($Value)
}

function Read-EnvFile {
    param(
        [string]$Path
    )

    $result = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $result
    }

    foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
        $text = [string]$line
        if ([string]::IsNullOrWhiteSpace($text)) {
            continue
        }
        if ($text.TrimStart().StartsWith('#')) {
            continue
        }
        $separatorIndex = $text.IndexOf('=')
        if ($separatorIndex -lt 1) {
            continue
        }
        $key = $text.Substring(0, $separatorIndex).Trim()
        $value = $text.Substring($separatorIndex + 1).Trim()
        $result[$key] = $value
    }

    return $result
}

function Write-EnvFile {
    param(
        [string]$Path,
        [System.Collections.Specialized.OrderedDictionary]$Entries
    )

    $preferredOrder = @(
        'DATABASE_URL',
        'SECRET_KEY',
        'IDS_DEFAULT_ADMIN_USERNAME',
        'IDS_DEFAULT_ADMIN_PASSWORD',
        'IDS_DEFAULT_ADMIN_REAL_NAME',
        'IDS_ACCEPTED_UPLOAD_DIR',
        'IDS_QUARANTINE_DIR',
        'IDS_REPORT_DIR',
        'IDS_OPERATOR_STATE_DIR',
        'IDS_AI_ANALYSIS',
        'IDS_BLOCK_THRESHOLD',
        'IDS_INTEGRATION_TOKEN',
        'IDS_GATEWAY_DEFAULT_PORT',
        'IDS_GATEWAY_FRONTEND_BASE_URL',
        'IDS_GATEWAY_BACKEND_BASE_URL',
        'IDS_GATEWAY_SITE_MAP',
        'IDS_GATEWAY_PORT_MAP',
        'LLM_PROVIDER',
        'LLM_BASE_URL',
        'LLM_API_KEY',
        'LLM_MODEL',
        'CORS_ORIGINS'
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# Generated by start-ids-docker.ps1')
    $lines.Add("# Generated at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    $lines.Add('')

    foreach ($key in $preferredOrder) {
        if ($Entries.Contains($key)) {
            $lines.Add("$key=$($Entries[$key])")
        }
    }

    foreach ($key in $Entries.Keys) {
        if ($preferredOrder -contains $key) {
            continue
        }
        $lines.Add("$key=$($Entries[$key])")
    }

    [System.IO.File]::WriteAllLines($Path, $lines, [System.Text.UTF8Encoding]::UTF8)
}

function To-IntOrDefault {
    param(
        $Value,
        [int]$Default
    )

    if ($null -eq $Value) {
        return $Default
    }

    $parsed = 0
    if ([int]::TryParse([string]$Value, [ref]$parsed) -and $parsed -ge 1 -and $parsed -le 65535) {
        return $parsed
    }

    return $Default
}

function Parse-UpstreamUrl {
    param(
        [string]$Url,
        [string]$FallbackHost,
        [int]$FallbackPort
    )

    if ([string]::IsNullOrWhiteSpace($Url)) {
        return @{
            Host = $FallbackHost
            Port = $FallbackPort
        }
    }

    $candidate = $Url.Trim()
    if ($candidate -notmatch '^[a-zA-Z][a-zA-Z0-9+\-.]*://') {
        $candidate = "http://$candidate"
    }

    try {
        $uri = [System.Uri]$candidate
        return @{
            Host = $uri.Host
            Port = $(if ($uri.IsDefaultPort) { $FallbackPort } else { $uri.Port })
        }
    } catch {
        return @{
            Host = $FallbackHost
            Port = $FallbackPort
        }
    }
}

function Build-UpstreamUrl {
    param(
        [string]$HostName,
        [int]$Port
    )

    return "http://$($HostName.Trim()):$Port"
}

function Convert-JsonArrayText {
    param(
        $Items
    )

    $rows = As-Array -Value $Items
    if ($rows.Count -eq 0) {
        return '[]'
    }

    $serialized = foreach ($item in $rows) {
        $item | ConvertTo-Json -Depth 12 -Compress
    }

    return '[' + ($serialized -join ',') + ']'
}

function Normalize-PortMappings {
    param(
        $Items
    )

    $rows = @()
    foreach ($item in (As-Array -Value $Items)) {
        if ($null -eq $item) {
            continue
        }

        $siteKey = [string](Get-PropValue -Object $item -Name 'site_key' -Default '')
        $displayName = [string](Get-PropValue -Object $item -Name 'display_name' -Default '')
        $ingressPort = To-IntOrDefault -Value (Get-PropValue -Object $item -Name 'ingress_port' -Default 0) -Default 0
        $frontendUpstream = [string](Get-PropValue -Object $item -Name 'frontend_upstream' -Default (Get-PropValue -Object $item -Name 'frontend_base_url' -Default ''))
        $backendUpstream = [string](Get-PropValue -Object $item -Name 'backend_upstream' -Default (Get-PropValue -Object $item -Name 'backend_base_url' -Default ''))

        if ([string]::IsNullOrWhiteSpace($siteKey) -or [string]::IsNullOrWhiteSpace($displayName)) {
            continue
        }
        if ($ingressPort -lt 1) {
            continue
        }
        if ([string]::IsNullOrWhiteSpace($frontendUpstream) -or [string]::IsNullOrWhiteSpace($backendUpstream)) {
            continue
        }

        $rows += [ordered]@{
            site_key = $siteKey.Trim()
            display_name = $displayName.Trim()
            ingress_port = $ingressPort
            frontend_upstream = $frontendUpstream.Trim()
            backend_upstream = $backendUpstream.Trim()
        }
    }

    return @($rows)
}

function Normalize-HostMappings {
    param(
        $Items
    )

    $rows = @()
    foreach ($item in (As-Array -Value $Items)) {
        if ($null -eq $item) {
            continue
        }

        $siteKey = [string](Get-PropValue -Object $item -Name 'site_key' -Default '')
        $displayName = [string](Get-PropValue -Object $item -Name 'display_name' -Default '')
        $frontendUpstream = [string](Get-PropValue -Object $item -Name 'frontend_upstream' -Default (Get-PropValue -Object $item -Name 'frontend_base_url' -Default ''))
        $backendUpstream = [string](Get-PropValue -Object $item -Name 'backend_upstream' -Default (Get-PropValue -Object $item -Name 'backend_base_url' -Default ''))
        $hosts = @((As-Array -Value (Get-PropValue -Object $item -Name 'hosts' -Default @())) | ForEach-Object {
            ([string]$_).Trim().ToLowerInvariant().TrimEnd('.')
        } | Where-Object { $_ }) | Select-Object -Unique

        if ([string]::IsNullOrWhiteSpace($siteKey) -or [string]::IsNullOrWhiteSpace($displayName)) {
            continue
        }
        if ($hosts.Count -eq 0) {
            continue
        }
        if ([string]::IsNullOrWhiteSpace($frontendUpstream) -or [string]::IsNullOrWhiteSpace($backendUpstream)) {
            continue
        }

        $rows += [ordered]@{
            site_key = $siteKey.Trim()
            display_name = $displayName.Trim()
            hosts = $hosts
            frontend_upstream = $frontendUpstream.Trim()
            backend_upstream = $backendUpstream.Trim()
        }
    }

    return @($rows)
}

function Prompt-Text {
    param(
        [string]$Label,
        [string]$Default = '',
        [switch]$AllowEmpty
    )

    if ($UseDefaults) {
        return [string]$Default
    }

    while ($true) {
        $suffix = if ([string]::IsNullOrWhiteSpace($Default)) { '' } else { " [$Default]" }
        $value = Read-Host "$Label$suffix"
        if ([string]::IsNullOrWhiteSpace($value)) {
            if ($AllowEmpty) {
                return ''
            }
            if (-not [string]::IsNullOrWhiteSpace($Default)) {
                return $Default
            }
            Write-Host '请输入内容。' -ForegroundColor Yellow
            continue
        }
        return $value.Trim()
    }
}

function Prompt-Port {
    param(
        [string]$Label,
        [int]$Default
    )

    if ($UseDefaults) {
        return [int]$Default
    }

    while ($true) {
        $value = Read-Host "$Label [$Default]"
        if ([string]::IsNullOrWhiteSpace($value)) {
            return [int]$Default
        }

        $parsed = 0
        if ([int]::TryParse($value.Trim(), [ref]$parsed) -and $parsed -ge 1 -and $parsed -le 65535) {
            return $parsed
        }

        Write-Host '端口必须是 1-65535 之间的整数。' -ForegroundColor Yellow
    }
}

function Prompt-Count {
    param(
        [string]$Label,
        [int]$Default = 0
    )

    if ($UseDefaults) {
        return $Default
    }

    while ($true) {
        $value = Read-Host "$Label [$Default]"
        if ([string]::IsNullOrWhiteSpace($value)) {
            return $Default
        }

        $parsed = 0
        if ([int]::TryParse($value.Trim(), [ref]$parsed) -and $parsed -ge 0) {
            return $parsed
        }

        Write-Host '请输入大于等于 0 的整数。' -ForegroundColor Yellow
    }
}

function Prompt-Bool {
    param(
        [string]$Label,
        [bool]$Default
    )

    if ($UseDefaults) {
        return $Default
    }

    $defaultText = if ($Default) { 'Y/n' } else { 'y/N' }

    while ($true) {
        $value = Read-Host "$Label [$defaultText]"
        if ([string]::IsNullOrWhiteSpace($value)) {
            return $Default
        }

        switch ($value.Trim().ToLowerInvariant()) {
            'y' { return $true }
            'yes' { return $true }
            '1' { return $true }
            'n' { return $false }
            'no' { return $false }
            '0' { return $false }
            default {
                Write-Host '请输入 y 或 n。' -ForegroundColor Yellow
            }
        }
    }
}

function Ensure-UniquePorts {
    param(
        [int]$GatewayPortValue,
        [System.Collections.IEnumerable]$PortMappings
    )

    $seen = New-Object System.Collections.Generic.HashSet[int]
    [void]$seen.Add($GatewayPortValue)

    foreach ($item in $PortMappings) {
        $port = [int](Get-PropValue -Object $item -Name 'ingress_port' -Default 0)
        if ($port -lt 1) {
            continue
        }
        if (-not $seen.Add($port)) {
            throw "检测到重复入口端口: $port"
        }
    }
}

function Ensure-UniqueHosts {
    param(
        [System.Collections.IEnumerable]$HostMappings
    )

    $seen = New-Object System.Collections.Generic.HashSet[string]
    foreach ($item in $HostMappings) {
        foreach ($host in (As-Array -Value (Get-PropValue -Object $item -Name 'hosts' -Default @()))) {
            $normalized = ([string]$host).Trim().ToLowerInvariant().TrimEnd('.')
            if ([string]::IsNullOrWhiteSpace($normalized)) {
                continue
            }
            if (-not $seen.Add($normalized)) {
                throw "检测到重复域名入口: $normalized"
            }
        }
    }
}

function New-OrderedDictionary {
    return New-Object System.Collections.Specialized.OrderedDictionary
}

function Add-OrUpdate {
    param(
        [System.Collections.Specialized.OrderedDictionary]$Dictionary,
        [string]$Key,
        [string]$Value
    )

    if ($Dictionary.Contains($Key)) {
        $Dictionary[$Key] = $Value
    } else {
        $Dictionary.Add($Key, $Value)
    }
}

function Get-Ipv4List {
    $addresses = @()

    try {
        $addresses = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object {
                $_.IPAddress -notlike '127.*' -and
                $_.IPAddress -notlike '169.254.*' -and
                $_.ValidLifetime -gt 0
            } |
            Sort-Object InterfaceMetric, SkipAsSource, IPAddress |
            Select-Object -ExpandProperty IPAddress -Unique
    } catch {
        $addresses = [System.Net.Dns]::GetHostAddresses([System.Net.Dns]::GetHostName()) |
            Where-Object {
                $_.AddressFamily -eq [System.Net.Sockets.AddressFamily]::InterNetwork -and
                $_.IPAddressToString -notlike '127.*'
            } |
            ForEach-Object { $_.IPAddressToString } |
            Select-Object -Unique
    }

    return @($addresses)
}

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw '未检测到 docker，请先安装 Docker Desktop 或 Docker Engine。'
}

$exampleEnv = Read-EnvFile -Path $envExamplePath
$currentEnv = Read-EnvFile -Path $envPath
$state = Read-JsonFile -Path $statePath

$envGatewayPort = To-IntOrDefault -Value $currentEnv['IDS_GATEWAY_DEFAULT_PORT'] -Default 8188
$frontendRuntime = Parse-UpstreamUrl -Url $currentEnv['IDS_GATEWAY_FRONTEND_BASE_URL'] -FallbackHost '127.0.0.1' -FallbackPort 5173
$backendRuntime = Parse-UpstreamUrl -Url $currentEnv['IDS_GATEWAY_BACKEND_BASE_URL'] -FallbackHost '127.0.0.1' -FallbackPort 8166

$stateReal = Get-PropValue -Object $state -Name 'real'
$stateDisplay = Get-PropValue -Object $state -Name 'display'

$defaultReal = [ordered]@{
    gateway_port = To-IntOrDefault -Value (Get-PropValue -Object $stateReal -Name 'gateway_port' -Default $envGatewayPort) -Default $envGatewayPort
    frontend_ip = [string](Get-PropValue -Object $stateReal -Name 'frontend_ip' -Default $frontendRuntime.Host)
    frontend_port = To-IntOrDefault -Value (Get-PropValue -Object $stateReal -Name 'frontend_port' -Default $frontendRuntime.Port) -Default $frontendRuntime.Port
    backend_ip = [string](Get-PropValue -Object $stateReal -Name 'backend_ip' -Default $backendRuntime.Host)
    backend_port = To-IntOrDefault -Value (Get-PropValue -Object $stateReal -Name 'backend_port' -Default $backendRuntime.Port) -Default $backendRuntime.Port
    default_site_key = [string](Get-PropValue -Object $stateReal -Name 'default_site_key' -Default 'campus_supply_chain')
    default_site_name = [string](Get-PropValue -Object $stateReal -Name 'default_site_name' -Default '校园供应链')
}

$defaultPortSites = Normalize-PortMappings -Items (Get-PropValue -Object $stateReal -Name 'extra_port_sites' -Default @())
if ($defaultPortSites.Count -eq 0 -and $currentEnv.Contains('IDS_GATEWAY_PORT_MAP')) {
    try {
        $defaultPortSites = Normalize-PortMappings -Items ($currentEnv['IDS_GATEWAY_PORT_MAP'] | ConvertFrom-Json)
    } catch {
        $defaultPortSites = @()
    }
}

$defaultHostSites = Normalize-HostMappings -Items (Get-PropValue -Object $stateReal -Name 'host_sites' -Default @())
if ($defaultHostSites.Count -eq 0 -and $currentEnv.Contains('IDS_GATEWAY_SITE_MAP')) {
    try {
        $defaultHostSites = Normalize-HostMappings -Items ($currentEnv['IDS_GATEWAY_SITE_MAP'] | ConvertFrom-Json)
    } catch {
        $defaultHostSites = @()
    }
}

$defaultDisplay = [ordered]@{
    site_label = [string](Get-PropValue -Object $stateDisplay -Name 'site_label' -Default '校园供应链主站')
    domain_code = [string](Get-PropValue -Object $stateDisplay -Name 'domain_code' -Default 'Campus-Link-A')
    link_template = [string](Get-PropValue -Object $stateDisplay -Name 'link_template' -Default '教学业务链路')
    routing_profile = [string](Get-PropValue -Object $stateDisplay -Name 'routing_profile' -Default '双向会话镜像')
    packet_profile = [string](Get-PropValue -Object $stateDisplay -Name 'packet_profile' -Default 'HTTP 会话封装')
    signal_band = [string](Get-PropValue -Object $stateDisplay -Name 'signal_band' -Default '基础频段')
    coordination_group = [string](Get-PropValue -Object $stateDisplay -Name 'coordination_group' -Default '校内协同单元')
    display_mode = [string](Get-PropValue -Object $stateDisplay -Name 'display_mode' -Default '总控视图')
    session_track_mode = [string](Get-PropValue -Object $stateDisplay -Name 'session_track_mode' -Default '连续轮转')
    trace_color_mode = [string](Get-PropValue -Object $stateDisplay -Name 'trace_color_mode' -Default '分层染色')
    link_sync_clock = [string](Get-PropValue -Object $stateDisplay -Name 'link_sync_clock' -Default '边界同步时钟')
    relay_group = [string](Get-PropValue -Object $stateDisplay -Name 'relay_group' -Default 'north-gateway')
    auto_rotate = [bool](Get-PropValue -Object $stateDisplay -Name 'auto_rotate' -Default $true)
    popup_broadcast = [bool](Get-PropValue -Object $stateDisplay -Name 'popup_broadcast' -Default $true)
    packet_shadow = [bool](Get-PropValue -Object $stateDisplay -Name 'packet_shadow' -Default $true)
    link_keepalive = [bool](Get-PropValue -Object $stateDisplay -Name 'link_keepalive' -Default $true)
}

$consolePortValue = if ($PSBoundParameters.ContainsKey('ConsolePort')) { $ConsolePort } else { To-IntOrDefault -Value $null -Default 5175 }
$apiPortValue = if ($PSBoundParameters.ContainsKey('ApiPort')) { $ApiPort } else { To-IntOrDefault -Value $null -Default 8170 }
$gatewayPortValue = if ($PSBoundParameters.ContainsKey('GatewayPort')) { $GatewayPort } else { $defaultReal.gateway_port }
$frontendIpValue = if ($PSBoundParameters.ContainsKey('FrontendIp')) { $FrontendIp } else { $defaultReal.frontend_ip }
$frontendPortValue = if ($PSBoundParameters.ContainsKey('FrontendPort')) { $FrontendPort } else { $defaultReal.frontend_port }
$backendIpValue = if ($PSBoundParameters.ContainsKey('BackendIp')) { $BackendIp } else { $defaultReal.backend_ip }
$backendPortValue = if ($PSBoundParameters.ContainsKey('BackendPort')) { $BackendPort } else { $defaultReal.backend_port }
$defaultSiteKeyValue = if ($PSBoundParameters.ContainsKey('DefaultSiteKey')) { $DefaultSiteKey } else { $defaultReal.default_site_key }
$defaultSiteNameValue = if ($PSBoundParameters.ContainsKey('DefaultSiteName')) { $DefaultSiteName } else { $defaultReal.default_site_name }
$displaySiteLabelValue = if ($PSBoundParameters.ContainsKey('DisplaySiteLabel')) { $DisplaySiteLabel } else { $defaultDisplay.site_label }
$domainCodeValue = if ($PSBoundParameters.ContainsKey('DomainCode')) { $DomainCode } else { $defaultDisplay.domain_code }

Write-Section -Title 'IDS Docker 通信配置启动器' -Description '将边界安全防线、核心业务平台和通信编排能力统一生成到 Docker 部署文件中。'

Write-Section -Title '第二阶段｜边界安全防线' -Description '配置默认入口、核心站点回源和 IDS 网关监听关系。这一组参数会真正决定流量怎样先经过 IDS 再进入目标站点。'
$gatewayPortValue = Prompt-Port -Label '默认入口端口' -Default $gatewayPortValue
$frontendIpValue = Prompt-Text -Label '默认前端回源 IP' -Default $frontendIpValue
$frontendPortValue = Prompt-Port -Label '默认前端回源端口' -Default $frontendPortValue
$backendIpValue = Prompt-Text -Label '默认后端回源 IP' -Default $backendIpValue
$backendPortValue = Prompt-Port -Label '默认后端回源端口' -Default $backendPortValue
$defaultSiteKeyValue = Prompt-Text -Label '默认站点标识' -Default $defaultSiteKeyValue
$defaultSiteNameValue = Prompt-Text -Label '默认站点名称' -Default $defaultSiteNameValue

Write-Section -Title '第三阶段｜核心业务平台' -Description '配置 IDS 控制台端口与 API 入口，用于容器化后的统一管理与状态查看。'
$consolePortValue = Prompt-Port -Label 'IDS 控制台对外端口' -Default $consolePortValue
$apiPortValue = Prompt-Port -Label 'IDS API 对外端口' -Default $apiPortValue

Write-Section -Title '第五阶段｜全流程联调与闭环验证' -Description '可选配置多站点端口入口和域名入口，适用于一套 IDS 管理多个业务入口的场景。'

$editPortMappings = Prompt-Bool -Label '是否重新配置附加端口入口映射' -Default $false
$portMappings = @()
if ($editPortMappings) {
    $portCount = Prompt-Count -Label '附加端口入口数量' -Default $defaultPortSites.Count
    for ($i = 0; $i -lt $portCount; $i++) {
        Write-Host ''
        Write-Host "附加端口入口 #$($i + 1)" -ForegroundColor Cyan
        $defaultItem = if ($i -lt $defaultPortSites.Count) { $defaultPortSites[$i] } else { $null }
        $siteKey = Prompt-Text -Label '  站点标识' -Default ([string](Get-PropValue -Object $defaultItem -Name 'site_key' -Default "site_$($i + 1)"))
        $displayName = Prompt-Text -Label '  站点名称' -Default ([string](Get-PropValue -Object $defaultItem -Name 'display_name' -Default "附加站点 $($i + 1)"))
        $ingressPort = Prompt-Port -Label '  入口端口' -Default (To-IntOrDefault -Value (Get-PropValue -Object $defaultItem -Name 'ingress_port' -Default (8288 + ($i * 100))) -Default (8288 + ($i * 100)))

        $defaultFrontend = Parse-UpstreamUrl -Url ([string](Get-PropValue -Object $defaultItem -Name 'frontend_upstream' -Default '')) -FallbackHost $frontendIpValue -FallbackPort $frontendPortValue
        $defaultBackend = Parse-UpstreamUrl -Url ([string](Get-PropValue -Object $defaultItem -Name 'backend_upstream' -Default '')) -FallbackHost $backendIpValue -FallbackPort $backendPortValue

        $extraFrontendIp = Prompt-Text -Label '  前端回源 IP' -Default $defaultFrontend.Host
        $extraFrontendPort = Prompt-Port -Label '  前端回源端口' -Default $defaultFrontend.Port
        $extraBackendIp = Prompt-Text -Label '  后端回源 IP' -Default $defaultBackend.Host
        $extraBackendPort = Prompt-Port -Label '  后端回源端口' -Default $defaultBackend.Port

        $portMappings += [ordered]@{
            site_key = $siteKey
            display_name = $displayName
            ingress_port = $ingressPort
            frontend_upstream = (Build-UpstreamUrl -HostName $extraFrontendIp -Port $extraFrontendPort)
            backend_upstream = (Build-UpstreamUrl -HostName $extraBackendIp -Port $extraBackendPort)
        }
    }
} else {
    foreach ($item in $defaultPortSites) {
        $portMappings += [ordered]@{
            site_key = [string](Get-PropValue -Object $item -Name 'site_key' -Default '')
            display_name = [string](Get-PropValue -Object $item -Name 'display_name' -Default '')
            ingress_port = To-IntOrDefault -Value (Get-PropValue -Object $item -Name 'ingress_port' -Default 0) -Default 8288
            frontend_upstream = [string](Get-PropValue -Object $item -Name 'frontend_upstream' -Default (Get-PropValue -Object $item -Name 'frontend_base_url' -Default ''))
            backend_upstream = [string](Get-PropValue -Object $item -Name 'backend_upstream' -Default (Get-PropValue -Object $item -Name 'backend_base_url' -Default ''))
        }
    }
}

 $portMappings = Normalize-PortMappings -Items $portMappings

$editHostMappings = Prompt-Bool -Label '是否重新配置域名入口映射' -Default $false
$hostMappings = @()
if ($editHostMappings) {
    $hostCount = Prompt-Count -Label '域名入口数量' -Default $defaultHostSites.Count
    for ($i = 0; $i -lt $hostCount; $i++) {
        Write-Host ''
        Write-Host "域名入口 #$($i + 1)" -ForegroundColor Cyan
        $defaultItem = if ($i -lt $defaultHostSites.Count) { $defaultHostSites[$i] } else { $null }
        $siteKey = Prompt-Text -Label '  站点标识' -Default ([string](Get-PropValue -Object $defaultItem -Name 'site_key' -Default "host_$($i + 1)"))
        $displayName = Prompt-Text -Label '  站点名称' -Default ([string](Get-PropValue -Object $defaultItem -Name 'display_name' -Default "域名站点 $($i + 1)"))
        $hostsDefault = (As-Array -Value (Get-PropValue -Object $defaultItem -Name 'hosts' -Default @())) -join ','
        $hostsCsv = Prompt-Text -Label '  域名列表(逗号分隔)' -Default $hostsDefault
        $hostNames = @($hostsCsv.Split(',') | ForEach-Object { $_.Trim().ToLowerInvariant().TrimEnd('.') } | Where-Object { $_ }) | Select-Object -Unique

        $defaultFrontend = Parse-UpstreamUrl -Url ([string](Get-PropValue -Object $defaultItem -Name 'frontend_upstream' -Default (Get-PropValue -Object $defaultItem -Name 'frontend_base_url' -Default ''))) -FallbackHost $frontendIpValue -FallbackPort $frontendPortValue
        $defaultBackend = Parse-UpstreamUrl -Url ([string](Get-PropValue -Object $defaultItem -Name 'backend_upstream' -Default (Get-PropValue -Object $defaultItem -Name 'backend_base_url' -Default ''))) -FallbackHost $backendIpValue -FallbackPort $backendPortValue

        $hostFrontendIp = Prompt-Text -Label '  前端回源 IP' -Default $defaultFrontend.Host
        $hostFrontendPort = Prompt-Port -Label '  前端回源端口' -Default $defaultFrontend.Port
        $hostBackendIp = Prompt-Text -Label '  后端回源 IP' -Default $defaultBackend.Host
        $hostBackendPort = Prompt-Port -Label '  后端回源端口' -Default $defaultBackend.Port

        $hostMappings += [ordered]@{
            site_key = $siteKey
            display_name = $displayName
            hosts = $hostNames
            frontend_upstream = (Build-UpstreamUrl -HostName $hostFrontendIp -Port $hostFrontendPort)
            backend_upstream = (Build-UpstreamUrl -HostName $hostBackendIp -Port $hostBackendPort)
        }
    }
} else {
    foreach ($item in $defaultHostSites) {
        $hostMappings += [ordered]@{
            site_key = [string](Get-PropValue -Object $item -Name 'site_key' -Default '')
            display_name = [string](Get-PropValue -Object $item -Name 'display_name' -Default '')
            hosts = @((As-Array -Value (Get-PropValue -Object $item -Name 'hosts' -Default @())) | ForEach-Object { ([string]$_).Trim().ToLowerInvariant().TrimEnd('.') } | Where-Object { $_ }) | Select-Object -Unique
            frontend_upstream = [string](Get-PropValue -Object $item -Name 'frontend_upstream' -Default (Get-PropValue -Object $item -Name 'frontend_base_url' -Default ''))
            backend_upstream = [string](Get-PropValue -Object $item -Name 'backend_upstream' -Default (Get-PropValue -Object $item -Name 'backend_base_url' -Default ''))
        }
    }
}

 $hostMappings = Normalize-HostMappings -Items $hostMappings

Write-Section -Title '第四阶段｜纵深主动防御与通信编排' -Description '这一组参数主要服务于通信配置中心、大屏、链路命名和态势编排展示；只有前面那组入口与回源参数直接改变转发路径。'

$editDisplaySettings = Prompt-Bool -Label '是否进入扩展通信编排配置' -Default $false
$displaySettings = [ordered]@{}
if ($editDisplaySettings) {
    $displaySettings.site_label = Prompt-Text -Label '站点名称' -Default $displaySiteLabelValue
    $displaySettings.domain_code = Prompt-Text -Label '通信域编号' -Default $domainCodeValue
    $displaySettings.link_template = Prompt-Text -Label '链路模板' -Default $defaultDisplay.link_template
    $displaySettings.routing_profile = Prompt-Text -Label '路由编排' -Default $defaultDisplay.routing_profile
    $displaySettings.packet_profile = Prompt-Text -Label '会话封装' -Default $defaultDisplay.packet_profile
    $displaySettings.signal_band = Prompt-Text -Label '频段标签' -Default $defaultDisplay.signal_band
    $displaySettings.coordination_group = Prompt-Text -Label '协同分组' -Default $defaultDisplay.coordination_group
    $displaySettings.display_mode = Prompt-Text -Label '展示模式' -Default $defaultDisplay.display_mode
    $displaySettings.session_track_mode = Prompt-Text -Label '会话轮转' -Default $defaultDisplay.session_track_mode
    $displaySettings.trace_color_mode = Prompt-Text -Label '轨迹染色' -Default $defaultDisplay.trace_color_mode
    $displaySettings.link_sync_clock = Prompt-Text -Label '同步时钟' -Default $defaultDisplay.link_sync_clock
    $displaySettings.relay_group = Prompt-Text -Label '中继分组' -Default $defaultDisplay.relay_group
    $displaySettings.auto_rotate = Prompt-Bool -Label '自动轮转' -Default $defaultDisplay.auto_rotate
    $displaySettings.popup_broadcast = Prompt-Bool -Label '弹窗播报' -Default $defaultDisplay.popup_broadcast
    $displaySettings.packet_shadow = Prompt-Bool -Label '数据包影子副本' -Default $defaultDisplay.packet_shadow
    $displaySettings.link_keepalive = Prompt-Bool -Label '链路保活' -Default $defaultDisplay.link_keepalive
} else {
    $displaySettings = [ordered]@{
        site_label = $displaySiteLabelValue
        domain_code = $domainCodeValue
        link_template = $defaultDisplay.link_template
        routing_profile = $defaultDisplay.routing_profile
        packet_profile = $defaultDisplay.packet_profile
        signal_band = $defaultDisplay.signal_band
        coordination_group = $defaultDisplay.coordination_group
        display_mode = $defaultDisplay.display_mode
        session_track_mode = $defaultDisplay.session_track_mode
        trace_color_mode = $defaultDisplay.trace_color_mode
        link_sync_clock = $defaultDisplay.link_sync_clock
        relay_group = $defaultDisplay.relay_group
        auto_rotate = $defaultDisplay.auto_rotate
        popup_broadcast = $defaultDisplay.popup_broadcast
        packet_shadow = $defaultDisplay.packet_shadow
        link_keepalive = $defaultDisplay.link_keepalive
    }
}

Ensure-UniquePorts -GatewayPortValue $gatewayPortValue -PortMappings $portMappings
Ensure-UniqueHosts -HostMappings $hostMappings

$frontendUpstream = Build-UpstreamUrl -HostName $frontendIpValue -Port $frontendPortValue
$backendUpstream = Build-UpstreamUrl -HostName $backendIpValue -Port $backendPortValue
$statePayload = [ordered]@{
    real = [ordered]@{
        gateway_port = $gatewayPortValue
        frontend_ip = $frontendIpValue
        frontend_port = $frontendPortValue
        backend_ip = $backendIpValue
        backend_port = $backendPortValue
        default_site_key = $defaultSiteKeyValue
        default_site_name = $defaultSiteNameValue
        extra_port_sites = [object[]]@($portMappings)
        host_sites = [object[]]@($hostMappings)
    }
    display = $displaySettings
    updated_at = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
}

[System.IO.File]::WriteAllText(
    $statePath,
    ($statePayload | ConvertTo-Json -Depth 12),
    [System.Text.UTF8Encoding]::UTF8
)

$mergedEnv = New-OrderedDictionary
foreach ($pair in $exampleEnv.GetEnumerator()) {
    $mergedEnv.Add([string]$pair.Key, [string]$pair.Value)
}
foreach ($pair in $currentEnv.GetEnumerator()) {
    Add-OrUpdate -Dictionary $mergedEnv -Key ([string]$pair.Key) -Value ([string]$pair.Value)
}

Add-OrUpdate -Dictionary $mergedEnv -Key 'DATABASE_URL' -Value 'sqlite:////data/ids.db'
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_ACCEPTED_UPLOAD_DIR' -Value '/data/uploads/accepted'
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_QUARANTINE_DIR' -Value '/data/quarantine'
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_REPORT_DIR' -Value '/data/reports'
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_OPERATOR_STATE_DIR' -Value '/data/state'
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_GATEWAY_DEFAULT_PORT' -Value ([string]$gatewayPortValue)
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_GATEWAY_FRONTEND_BASE_URL' -Value $frontendUpstream
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_GATEWAY_BACKEND_BASE_URL' -Value $backendUpstream
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_GATEWAY_PORT_MAP' -Value (Convert-JsonArrayText -Items $portMappings)
Add-OrUpdate -Dictionary $mergedEnv -Key 'IDS_GATEWAY_SITE_MAP' -Value (Convert-JsonArrayText -Items $hostMappings)
Add-OrUpdate -Dictionary $mergedEnv -Key 'CORS_ORIGINS' -Value (
    Convert-JsonArrayText -Items @(
        "http://localhost:$consolePortValue",
        "http://127.0.0.1:$consolePortValue",
        'http://localhost:8081',
        'http://127.0.0.1:8081'
    )
)

Write-EnvFile -Path $envPath -Entries $mergedEnv

$gatewayPorts = @($gatewayPortValue) + @(As-Array -Value $portMappings | ForEach-Object { [int]$_.ingress_port })
$gatewayPorts = $gatewayPorts | Select-Object -Unique | Sort-Object
$gatewayPortBlock = ($gatewayPorts | ForEach-Object { "      - ""$($_):8188""" }) -join "`n"

$composeContent = @"
services:
  ids-backend:
    build:
      context: ./ids-backend
    restart: unless-stopped
    ports:
      - "$($apiPortValue):8170"
    volumes:
      - ./config/ids-backend.env:/app/.env
      - ./ids-data:/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8170/api/health', timeout=5)"]
      interval: 15s
      timeout: 5s
      retries: 8
      start_period: 20s

  ids-gateway:
    build:
      context: ./ids-backend
    restart: unless-stopped
    command: ["uvicorn", "app.gateway_main:app", "--host", "0.0.0.0", "--port", "8188"]
    depends_on:
      ids-backend:
        condition: service_healthy
    volumes:
      - ./config/ids-backend.env:/app/.env
      - ./ids-data:/data
    ports:
$gatewayPortBlock
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8188/gateway/health', timeout=5)"]
      interval: 15s
      timeout: 5s
      retries: 8
      start_period: 20s

  ids-frontend:
    build:
      context: ./ids-frontend
    restart: unless-stopped
    depends_on:
      ids-backend:
        condition: service_healthy
    ports:
      - "$($consolePortValue):80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 8
      start_period: 10s
"@

[System.IO.File]::WriteAllText($composePath, $composeContent.Trim() + [Environment]::NewLine, [System.Text.UTF8Encoding]::UTF8)

Write-Section -Title '第五阶段｜生成结果校验' -Description '正在校验 Docker Compose 文件结构与容器依赖关系。'
docker compose --project-directory $packageRoot -f $composePath config | Out-Null
Write-Host '[ok] docker-compose.generated.yml 已通过语法校验。' -ForegroundColor Green

Write-Host ''
Write-Host '重点运行参数' -ForegroundColor Yellow
Write-Host "  默认入口端口: $gatewayPortValue"
Write-Host "  默认前端回源: $frontendUpstream"
Write-Host "  默认后端回源: $backendUpstream"
Write-Host "  附加端口入口数量: $($portMappings.Count)"
Write-Host "  域名入口数量: $($hostMappings.Count)"
Write-Host ''
Write-Host '控制台编排参数' -ForegroundColor Yellow
Write-Host "  站点名称: $($displaySettings.site_label)"
Write-Host "  通信域编号: $($displaySettings.domain_code)"
Write-Host "  链路模板: $($displaySettings.link_template)"
Write-Host "  展示模式: $($displaySettings.display_mode)"
Write-Host ''
Write-Host "配置文件: $envPath" -ForegroundColor Gray
Write-Host "状态文件: $statePath" -ForegroundColor Gray
Write-Host "Compose 文件: $composePath" -ForegroundColor Gray

if ($SkipStart) {
    Write-Host ''
    Write-Host '[info] 已按要求仅生成配置文件，未启动 Docker 容器。' -ForegroundColor Yellow
    exit 0
}

Write-Section -Title '容器启动中' -Description '将按当前通信配置拉起 IDS 后端、IDS 网关与 IDS 控制台。'
docker compose --project-directory $packageRoot -f $composePath up -d --build

Start-Sleep -Seconds 6

$healthChecks = @(
    @{ Name = 'IDS Frontend'; Url = "http://127.0.0.1:$consolePortValue/" },
    @{ Name = 'IDS Backend'; Url = "http://127.0.0.1:$apiPortValue/api/health" },
    @{ Name = 'IDS Gateway'; Url = "http://127.0.0.1:$gatewayPortValue/gateway/health" }
)

Write-Host ''
Write-Host '服务探测结果' -ForegroundColor Cyan
foreach ($item in $healthChecks) {
    try {
        $response = Invoke-WebRequest -Uri $item.Url -UseBasicParsing -TimeoutSec 8
        Write-Host "  [ok] $($item.Name): $($response.StatusCode) $($item.Url)" -ForegroundColor Green
    } catch {
        Write-Host "  [warn] $($item.Name): 启动后未立即通过探测 $($item.Url)" -ForegroundColor Yellow
    }
}

$ipv4List = Get-Ipv4List
if ($ipv4List.Count -gt 0) {
    Write-Host ''
    Write-Host '本机 IPv4 地址' -ForegroundColor Cyan
    foreach ($ip in $ipv4List) {
        Write-Host "  $ip"
    }

    Write-Host ''
    Write-Host '访问示例' -ForegroundColor Cyan
    foreach ($ip in $ipv4List | Select-Object -First 2) {
        Write-Host "  IDS 网关:  http://${ip}:$gatewayPortValue"
        Write-Host "  IDS 控制台: http://${ip}:$consolePortValue"
    }
}

Write-Host ''
Write-Host '如果后续你在 Web 通信配置中心改了默认入口端口或附加端口入口，请重新执行本脚本以重新生成 Docker 端口映射。' -ForegroundColor Yellow








